name: Enhancement ✨
description: Suggest an enhancement to an existing feature
labels: [kind/enhancement ✨]

body:
  - type: markdown
    attributes:
      value: |
        Before opening a new enhancement, please search for potential existing issues.

        ---

        Thank you for taking the time to file an enhancement request, we appreciate and value your time to help the project!

  - type: textarea
    id: problem
    attributes:
      label: Is your enhancement related to a problem? Please describe
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots here.
