FROM quay.io/centos-bootc/fedora-bootc:eln

# Add the podman quadlet systemd service
ADD helloworld.container /usr/share/containers/systemd/helloworld.container

# Change the root password so I can login
RUN echo "root:root" | chpasswd