FROM quay.io/centos-bootc/centos-bootc-dev:stream9

# Add the systemd service
ADD helloworld.service /usr/lib/systemd/system/helloworld.service

# Enable the service
RUN systemctl enable helloworld

# Add the helloworld example
ADD helloworld.py /usr/bin/helloworld.py

# Change the root password so I can login
RUN echo "root:root" | chpasswd